plugins {
    id 'com.android.application'
}

android {
    namespace 'com.chengvar.zocode'
    compileSdk 35

    defaultConfig {
        applicationId 'com.chengvar.zocode'
        minSdk 24
        targetSdk 35
        versionCode 1
        versionName '1.0'
    }

    signingConfigs {
        release {
            storeFile rootProject.file('zocode.keystore')
            storePassword 'zocode123'
            keyAlias 'zocode'
            keyPassword 'zocode123'
        }
    }

    buildTypes {
        release {
            minifyEnabled false
            signingConfig signingConfigs.release
        }
    }

    lint {
        checkReleaseBuilds false
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}
