plugins {
    id 'com.android.application'
}

android {
    namespace 'com.chengvar.zocode'
    compileSdk 35

    defaultConfig {
        applicationId 'com.chengvar.zocode'
        minSdk 34
        targetSdk 35
        versionCode 1
        versionName '1.0'
    }

    signingConfigs {
        release {
            storeFile rootProject.file('zocode.keystore')
            storePassword 'zocode123'
            keyAlias 'zocode'
            keyPassword 'zocode123'
        }
    }

    buildTypes {
        release {
            minifyEnabled false
            signingConfig signingConfigs.release
        }
    }

    lint {
        checkReleaseBuilds false
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}

dependencies {
    constraints {
        implementation('org.jetbrains.kotlin:kotlin-stdlib-jdk8:1.8.22') {
            because 'kotlin-stdlib 1.8 已合并 jdk7/jdk8 模块'
        }
        implementation('org.jetbrains.kotlin:kotlin-stdlib-jdk7:1.8.22') {
            because 'kotlin-stdlib 1.8 已合并 jdk7/jdk8 模块'
        }
    }
    implementation 'androidx.appcompat:appcompat:1.7.0'
    implementation 'com.google.zxing:core:3.5.3'
    implementation 'com.journeyapps:zxing-android-embedded:4.3.0'
}
